import type { Metadata } from 'next';
import './globals.css';
import { SideNavigation } from './components/SideNavigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <div className="flex">
          <SideNavigation />
          <main className="ml-[240px] w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
